#!/usr/bin/env python3
"""文献全文获取器。

对 arXiv 条目下载 e-print 源码包（LaTeX 原文，`https://arxiv.org/e-print/<id>`），对非 arXiv 条目
下载出版方或作者提供的 PDF 全文，一律解包/转文本后落到本机工作目录，供逐条核对引文。

**全文不入库**：第三方论文的源码包与 PDF 不随本仓库分发。入库的是 `lit/manifest.csv`（每篇的
标识、版本、URL、字节数、SHA-256）与 `lit/quotes.md`（本报告实际引用的逐条原文及其出处位置），
使任何人都能自行取得同一份文件、用校验和确认版本一致，再核对引文。

用法：
    python3 scripts/fetch_literature.py            # 下载并解包到 WORKDIR
    python3 scripts/fetch_literature.py --list     # 仅打印待取清单
环境变量：
    LIT_WORKDIR   工作目录，默认 /tmp/lit
    http_proxy / https_proxy   若本机需代理访问 arxiv.org 则设置
"""
from __future__ import annotations

import csv
import hashlib
import os
import re
import subprocess
import sys
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIT = ROOT / "lit"
LIT.mkdir(exist_ok=True)
WORK = Path(os.environ.get("LIT_WORKDIR", "/tmp/lit"))
WORK.mkdir(parents=True, exist_ok=True)

# 文献清单。tier=1 表示本报告直接引用其数值、必须核对全文；tier=2 表示引用其定性结论。
# 「arxiv」取 e-print 源码包；「pdf」取给定 URL 的 PDF 全文。
LITERATURE = [
    # ---- AI code review / agent 实证（全部 tier 1：本报告引用其具体数值）----
    ("2604.22273", "arxiv", 1, "Self-Correction as Feedback Control: Error Dynamics, Stability Thresholds, and Prompt Interventions in LLMs"),
    ("2604.03196", "arxiv", 1, "From Industry Claims to Empirical Reality: An Empirical Study of Code Review Agents in Pull Requests"),
    ("2607.03316", "arxiv", 1, "Is Agentic Code Review Helpful? Mining Developers' Feedback to CodeRabbit Reviews in the Wild"),
    ("2606.22721", "arxiv", 1, "Habituation at the Gate: Rising Approval and Declining Scrutiny in Human Review of AI Agent Code"),
    ("2607.01641", "arxiv", 1, "When Agents Do Not Stop: Uncovering Infinite Agentic Loops in LLM Agents"),
    ("2602.09185", "arxiv", 1, "AIDev: Studying AI Coding Agents on GitHub"),
    ("2602.08915", "arxiv", 1, "Comparing AI Coding Agents: A Task-Stratified Analysis of Pull Request Acceptance"),
    ("2606.13468", "arxiv", 1, "Understanding the Rejection of Fixes Generated by Agentic Pull Requests"),
    ("2604.24450", "arxiv", 2, "On the Footprints of Reviewer Bots Feedback on Agentic Pull Requests in OSS GitHub Repositories"),
    ("2605.17548", "arxiv", 2, "Rethinking Code Review in the Age of AI: A Vision for Agentic Code Review"),
    # ---- LLM 自我纠错 / 迭代精修 ----
    ("2310.01798", "arxiv", 1, "Large Language Models Cannot Self-Correct Reasoning Yet"),
    ("2407.04549", "arxiv", 1, "Spontaneous Reward Hacking in Iterative Self-Refinement"),
    ("2402.11436", "arxiv", 2, "Pride and Prejudice: LLM Amplifies Self-Bias in Self-Refinement"),
    ("2303.17651", "arxiv", 2, "Self-Refine: Iterative Refinement with Self-Feedback"),
    # ---- 人类 code review 实证（非 arXiv，取作者/出版方 PDF）----
    ("sadowski2018", "pdf", 1, "Modern Code Review: A Case Study at Google",
     "https://sback.it/publications/icse2018seip.pdf"),
    ("rigby2013", "pdf", 1, "Convergent Contemporary Software Peer Review Practices",
     "https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/rigby2013convergent.pdf"),
    ("bacchelli2013", "pdf", 1, "Expectations, Outcomes, and Challenges of Modern Code Review",
     "https://sback.it/publications/icse2013.pdf"),
    ("bosu2015", "pdf", 1, "Characteristics of Useful Code Reviews: An Empirical Study at Microsoft",
     "https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/bosu2015useful.pdf"),
    ("gousios2015", "pdf", 1, "Work Practices and Challenges in Pull-Based Development: The Integrator's Perspective",
     "https://azaidman.github.io/publications/gousiosICSE2015.pdf"),
    ("gousios2016", "pdf", 2, "Work Practices and Challenges in Pull-Based Development: The Contributor's Perspective",
     "https://sback.it/publications/icse2016b.pdf"),
    ("yu2015", "pdf", 1, "Wait For It: Determinants of Pull Request Evaluation Latency on GitHub",
     "https://yuyue.github.io/res/paper/msr2015.pdf"),
    ("thongtanunam2016", "pdf", 2, "Review Participation in Modern Code Review",
     "https://sailresearch.github.io/sail-website/data/pdfs/EMSE2016_ReviewParticipationInModernCodeReviewAnEmpiricalStudyOfTheAndroidQtAndOpenStackProjects.pdf"),
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def curl(url: str, dest: Path) -> bool:
    proc = subprocess.run(
        ["curl", "-sL", "--max-time", "180", "-o", str(dest), url],
        capture_output=True, text=True)
    return proc.returncode == 0 and dest.exists() and dest.stat().st_size > 2048


def untar_tex(archive: Path, outdir: Path) -> list[str]:
    """解 arXiv e-print 包。多数是 .tar.gz；少数单文件投稿是裸 .tex.gz 或纯 PDF。"""
    outdir.mkdir(parents=True, exist_ok=True)
    try:
        with tarfile.open(archive) as tf:
            members = [m for m in tf.getmembers() if m.isfile()]
            for m in members:
                m.name = os.path.basename(m.name)
            tf.extractall(outdir, members=members)
        return sorted(p.name for p in outdir.iterdir())
    except tarfile.ReadError:
        # 裸 gzip 单文件
        import gzip
        try:
            data = gzip.decompress(archive.read_bytes())
        except OSError:
            return []
        (outdir / "main.tex").write_bytes(data)
        return ["main.tex"]


def main() -> None:
    if "--list" in sys.argv:
        for row in LITERATURE:
            print(f"tier{row[2]}  {row[1]:5s}  {row[0]:16s}  {row[3][:70]}")
        return
    rows = []
    for entry in LITERATURE:
        key, kind, tier, title = entry[0], entry[1], entry[2], entry[3]
        if kind == "arxiv":
            url = f"https://arxiv.org/e-print/{key}"
            dest = WORK / f"{key}.tar.gz"
        else:
            url = entry[4]
            dest = WORK / f"{key}.pdf"
        if not dest.exists() and not curl(url, dest):
            print(f"  取失败 {key} <- {url}")
            rows.append({"key": key, "kind": kind, "tier": tier, "title": title,
                         "url": url, "bytes": 0, "sha256": "FETCH_FAILED",
                         "extracted_to": ""})
            continue
        digest, size = sha256(dest), dest.stat().st_size
        if kind == "arxiv":
            files = untar_tex(dest, WORK / key)
            tex = [f for f in files if f.endswith(".tex")]
            # LaTeX 源码里的正文即可直接读；同时生成一份合并纯文本便于全文检索
            merged = WORK / f"{key}.txt"
            merged.write_text("\n\n".join(
                (WORK / key / f).read_text(errors="replace") for f in tex), errors="replace")
            note = f"{len(tex)} tex -> {merged.name}"
        else:
            txt = WORK / f"{key}.txt"
            subprocess.run(["pdftotext", "-layout", str(dest), str(txt)],
                           capture_output=True)
            note = f"{txt.name} ({txt.stat().st_size if txt.exists() else 0} B)"
        print(f"  ok {key:16s} {size:>9d} B  {note}")
        rows.append({"key": key, "kind": kind, "tier": tier, "title": title,
                     "url": url, "bytes": size, "sha256": digest,
                     "extracted_to": note})
    with (LIT / "manifest.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["key", "kind", "tier", "title", "url",
                                          "bytes", "sha256", "extracted_to"])
        w.writeheader()
        w.writerows(rows)
    ok = sum(1 for r in rows if r["sha256"] != "FETCH_FAILED")
    print(f"清单写入 lit/manifest.csv：{ok}/{len(rows)} 篇取得全文")


if __name__ == "__main__":
    main()
